name: recipe_extractor
description: Retrieve recipe name, ingredients and instructions from a recipe URL.
version: 1.0.1
repository: https://github.com/judemont/recipe_extractor

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  html: ^0.15.4
  http: ^1.2.1
  web: ^0.5.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
